# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-14 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip_planner',
            old_name='trip',
            new_name='trips',
        ),
    ]
