# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-14 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0002_auto_20171214_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip_planner',
            old_name='trip_planner',
            new_name='trip_maker',
        ),
    ]
