# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-15 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0003_auto_20171214_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip_planner',
            name='joined_trip',
            field=models.BooleanField(default=False),
        ),
    ]
